### PR TITLE
Add app name and device name to window title

### PR DESCRIPTION
**Pull request by huntie**
# Summary

> [!Note]
> Depends on https://github.com/facebookexperimental/rn-chrome-devtools-frontend/pull/86 and https://github.com/facebook/react-native/pull/45250.

Updates the `rn_fusebox` entrypoint to update the window title if the device returns identifying metadata via `ReactNativeApplication.metadataUpdated`. This signals the current **app name** and **device name** to the user! 🎉

Resolves [T165849560](https://www.internalfb.com/intern/tasks/?t=165849560).

> [!Note]
> **Known issue** — `ReactNativeApplicationModel` is mounted within the Welcome panel, meaning this behaviour won't trigger if opened to another panel. This needs to be relocated in a later PR — likely having some model within the entrypoint inherit from this (or however the data flow can work). **However**, I want to land this change (see #88 for where we do make use of this in `RNWelcome.ts`) so we have incremental progress.

# Test plan

Connect to Android and iOS after https://github.com/facebook/react-native/pull/45250.

image

# Upstreaming plan

- [ ] This commit should be sent as a patch to the upstream `devtools-frontend` repo. I've reviewed the [contribution guide](https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/edit#heading=h.9kj7femz1xg5).
- [x] This commit is React Native-specific and cannot be upstreamed.

### CODE REVIEW

**Review by hoxyq — COMMENTED** [review]
Can you try making `ReactNativeApplicationModel` as part of the SDK? I believe this way it should start automatically, together with other required models, such as `RuntimeModel`:
https://github.com/facebookexperimental/rn-chrome-devtools-frontend/blob/b1ab9e1f8a9b50cb2df3aeb48a50019e6e535294/front_end/core/sdk/sdk.ts#L5-L11

**Comment by huntie** [comment]
@hoxyq I can do 👍🏻 Alright if I stack this on top of https://github.com/facebookexperimental/rn-chrome-devtools-frontend/pull/88?

**Comment by hoxyq** [comment]
> Can you try making `ReactNativeApplicationModel` part of the SDK? I believe this way it should start automatically, together with other required models, such as `RuntimeModel`:
> 
> https://github.com/facebookexperimental/rn-chrome-devtools-frontend/blob/b1ab9e1f8a9b50cb2df3aeb48a50019e6e535294/front_end/core/sdk/sdk.ts#L5-L11

Oh, I think I was wrong, its probably better to register model in rn_fusebox.ts, the way we do it for FuseboxClientMetadata model:
https://github.com/facebookexperimental/rn-chrome-devtools-frontend/blob/7cd81c1548a4bca19732037dcf82662a6ed9ca39/front_end/entrypoints/rn_fusebox/rn_fusebox.ts#L108-L121

**Review by hoxyq — APPROVED** [review]
Model initialization logic is refactored in https://github.com/facebookexperimental/rn-chrome-devtools-frontend/pull/90/

**Pull request merged**
